// Generated by CoffeeScript 1.3.3
(function() {
  var Bender;

  Bender = {
    Module: require('./module'),
    Events: require('./events'),
    Logger: require('./logger')
  };

  module.exports = Bender;

}).call(this);
